import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import { UserDataProvider } from "@/context/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-yellow-50 via-orange-50 to-yellow-100`}
      >
        <UserDataProvider>
          <Header />
          <main className="font-sans container  mt-4 min-h-screen  gap-16 mx-auto">
            {children}
          </main>
        </UserDataProvider>
        <Footer />
        {/* <footer className="row-start-3 flex items-center justify-center container mx-auto p-4  font-poppins font-semibold">
          <p className="text-gray-600">
            © {new Date().getFullYear()} Contact HUB. All rights reserved.
          </p>
        </footer> */}
        {/* <div className="text-center mt-6 text-gray-600 text-sm">
          © 2025 Contact HUB. All rights reserved.
        </div> */}
      </body>
    </html>
  );
}
